#############################################################################
# Makefile for building: GA6
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  GA6.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile GA6.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtCharts -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = GA61.0.0
DISTDIR = /home/aleksa/GA_CST/.tmp/GA61.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lglut -lGLU /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so /usr/lib/x86_64-linux-gnu/libQt5Charts.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = algoritambaza.cpp \
		algoritmi_sa_vezbi/ga00_demoiscrtavanja.cpp \
		algoritmi_sa_vezbi/ga01_brisucaprava.cpp \
		algoritmi_sa_vezbi/ga02_3discrtavanje.cpp \
		algoritmi_sa_vezbi/ga03_konveksniomotac.cpp \
		algoritmi_sa_vezbi/ga04_konveksniomotac3d.cpp \
		algoritmi_sa_vezbi/ga05_preseciduzi.cpp \
		algoritmi_sa_vezbi/ga06_dcel.cpp \
		algoritmi_sa_vezbi/ga06_dceldemo.cpp \
		algoritmi_sa_vezbi/ga07_triangulation.cpp \
		algoritmi_sa_vezbi/constant_work_space.cpp \
		algoritmi_studentski_projekti/ga06_presekPravougaonika.cpp \
		animacijanit.cpp \
		main.cpp \
		mainwindow.cpp \
		oblastcrtanja.cpp \
		oblastcrtanjaopengl.cpp \
		pomocnefunkcije.cpp \
		timemeasurementthread.cpp moc_algoritambaza.cpp \
		moc_mainwindow.cpp \
		moc_oblastcrtanja.cpp \
		moc_oblastcrtanjaopengl.cpp \
		moc_timemeasurementthread.cpp
OBJECTS       = algoritambaza.o \
		ga00_demoiscrtavanja.o \
		ga01_brisucaprava.o \
		ga02_3discrtavanje.o \
		ga03_konveksniomotac.o \
		ga04_konveksniomotac3d.o \
		ga05_preseciduzi.o \
		ga06_dcel.o \
		ga06_dceldemo.o \
		ga07_triangulation.o \
		constant_work_space.o \
		ga06_presekPravougaonika.o \
		animacijanit.o \
		main.o \
		mainwindow.o \
		oblastcrtanja.o \
		oblastcrtanjaopengl.o \
		pomocnefunkcije.o \
		timemeasurementthread.o \
		moc_algoritambaza.o \
		moc_mainwindow.o \
		moc_oblastcrtanja.o \
		moc_oblastcrtanjaopengl.o \
		moc_timemeasurementthread.o
DIST          = docs/ga06_presekPravougaonika.docx \
		docs/ga06_presekPravougaonika.pdf \
		input_files/ga00_DCELDemo/mushroom.off \
		input_files/ga00_DCELDemo/test0.off \
		input_files/ga00_KonveksniOmotac3D/input1.txt \
		input_files/ga06_presekPravougaonika/input1.txt \
		input_files/ga06_presekPravougaonika/input2.txt \
		input_files/ga06_presekPravougaonika/input3.txt \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		GA6.pro algoritambaza.h \
		algoritmi_sa_vezbi/ga00_demoiscrtavanja.h \
		algoritmi_sa_vezbi/ga01_brisucaprava.h \
		algoritmi_sa_vezbi/ga02_3discrtavanje.h \
		algoritmi_sa_vezbi/ga03_konveksniomotac.h \
		algoritmi_sa_vezbi/ga04_konveksni3dDatastructures.h \
		algoritmi_sa_vezbi/ga04_konveksniomotac3d.h \
		algoritmi_sa_vezbi/ga05_datastructures.h \
		algoritmi_sa_vezbi/ga05_preseciduzi.h \
		algoritmi_sa_vezbi/ga06_dcel.h \
		algoritmi_sa_vezbi/ga06_dceldemo.h \
		algoritmi_sa_vezbi/ga07_datastructures.h \
		algoritmi_sa_vezbi/ga07_triangulation.h \
		algoritmi_sa_vezbi/constant_work_space.h \
		algoritmi_studentski_projekti/ga06_presekPravougaonika.h \
		animacijanit.h \
		config.h \
		mainwindow.h \
		oblastcrtanja.h \
		oblastcrtanjaopengl.h \
		pomocnefunkcije.h \
		timemeasurementthread.h algoritambaza.cpp \
		algoritmi_sa_vezbi/ga00_demoiscrtavanja.cpp \
		algoritmi_sa_vezbi/ga01_brisucaprava.cpp \
		algoritmi_sa_vezbi/ga02_3discrtavanje.cpp \
		algoritmi_sa_vezbi/ga03_konveksniomotac.cpp \
		algoritmi_sa_vezbi/ga04_konveksniomotac3d.cpp \
		algoritmi_sa_vezbi/ga05_preseciduzi.cpp \
		algoritmi_sa_vezbi/ga06_dcel.cpp \
		algoritmi_sa_vezbi/ga06_dceldemo.cpp \
		algoritmi_sa_vezbi/ga07_triangulation.cpp \
		algoritmi_sa_vezbi/constant_work_space.cpp \
		algoritmi_studentski_projekti/ga06_presekPravougaonika.cpp \
		animacijanit.cpp \
		main.cpp \
		mainwindow.cpp \
		oblastcrtanja.cpp \
		oblastcrtanjaopengl.cpp \
		pomocnefunkcije.cpp \
		timemeasurementthread.cpp
QMAKE_TARGET  = GA6
DESTDIR       = 
TARGET        = GA6


first: all
####### Build rules

GA6: ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GA6.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		GA6.pro
	$(QMAKE) -o Makefile GA6.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
GA6.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile GA6.pro

qmake_all: FORCE


all: Makefile GA6

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents algoritambaza.h algoritmi_sa_vezbi/ga00_demoiscrtavanja.h algoritmi_sa_vezbi/ga01_brisucaprava.h algoritmi_sa_vezbi/ga02_3discrtavanje.h algoritmi_sa_vezbi/ga03_konveksniomotac.h algoritmi_sa_vezbi/ga04_konveksni3dDatastructures.h algoritmi_sa_vezbi/ga04_konveksniomotac3d.h algoritmi_sa_vezbi/ga05_datastructures.h algoritmi_sa_vezbi/ga05_preseciduzi.h algoritmi_sa_vezbi/ga06_dcel.h algoritmi_sa_vezbi/ga06_dceldemo.h algoritmi_sa_vezbi/ga07_datastructures.h algoritmi_sa_vezbi/ga07_triangulation.h algoritmi_sa_vezbi/constant_work_space.h algoritmi_studentski_projekti/ga06_presekPravougaonika.h animacijanit.h config.h mainwindow.h oblastcrtanja.h oblastcrtanjaopengl.h pomocnefunkcije.h timemeasurementthread.h $(DISTDIR)/
	$(COPY_FILE) --parents algoritambaza.cpp algoritmi_sa_vezbi/ga00_demoiscrtavanja.cpp algoritmi_sa_vezbi/ga01_brisucaprava.cpp algoritmi_sa_vezbi/ga02_3discrtavanje.cpp algoritmi_sa_vezbi/ga03_konveksniomotac.cpp algoritmi_sa_vezbi/ga04_konveksniomotac3d.cpp algoritmi_sa_vezbi/ga05_preseciduzi.cpp algoritmi_sa_vezbi/ga06_dcel.cpp algoritmi_sa_vezbi/ga06_dceldemo.cpp algoritmi_sa_vezbi/ga07_triangulation.cpp algoritmi_sa_vezbi/constant_work_space.cpp algoritmi_studentski_projekti/ga06_presekPravougaonika.cpp animacijanit.cpp main.cpp mainwindow.cpp oblastcrtanja.cpp oblastcrtanjaopengl.cpp pomocnefunkcije.cpp timemeasurementthread.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1y -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_algoritambaza.cpp moc_mainwindow.cpp moc_oblastcrtanja.cpp moc_oblastcrtanjaopengl.cpp moc_timemeasurementthread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_algoritambaza.cpp moc_mainwindow.cpp moc_oblastcrtanja.cpp moc_oblastcrtanjaopengl.cpp moc_timemeasurementthread.cpp
moc_algoritambaza.cpp: algoritambaza.h \
		animacijanit.h \
		config.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/aleksa/GA_CST/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/aleksa/GA_CST -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include algoritambaza.h -o moc_algoritambaza.cpp

moc_mainwindow.cpp: mainwindow.h \
		algoritambaza.h \
		animacijanit.h \
		config.h \
		oblastcrtanja.h \
		oblastcrtanjaopengl.h \
		timemeasurementthread.h \
		algoritmi_sa_vezbi/ga00_demoiscrtavanja.h \
		algoritmi_sa_vezbi/ga01_brisucaprava.h \
		algoritmi_sa_vezbi/ga02_3discrtavanje.h \
		algoritmi_sa_vezbi/ga03_konveksniomotac.h \
		algoritmi_sa_vezbi/ga04_konveksniomotac3d.h \
		algoritmi_sa_vezbi/ga04_konveksni3dDatastructures.h \
		algoritmi_sa_vezbi/ga05_preseciduzi.h \
		pomocnefunkcije.h \
		algoritmi_sa_vezbi/ga05_datastructures.h \
		algoritmi_sa_vezbi/ga06_dceldemo.h \
		algoritmi_sa_vezbi/ga06_dcel.h \
		algoritmi_sa_vezbi/ga07_triangulation.h \
		algoritmi_sa_vezbi/ga07_datastructures.h \
		algoritmi_sa_vezbi/constant_work_space.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/aleksa/GA_CST/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/aleksa/GA_CST -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_oblastcrtanja.cpp: oblastcrtanja.h \
		algoritambaza.h \
		animacijanit.h \
		config.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/aleksa/GA_CST/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/aleksa/GA_CST -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include oblastcrtanja.h -o moc_oblastcrtanja.cpp

moc_oblastcrtanjaopengl.cpp: oblastcrtanjaopengl.h \
		algoritambaza.h \
		animacijanit.h \
		config.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/aleksa/GA_CST/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/aleksa/GA_CST -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include oblastcrtanjaopengl.h -o moc_oblastcrtanjaopengl.cpp

moc_timemeasurementthread.cpp: timemeasurementthread.h \
		algoritambaza.h \
		animacijanit.h \
		config.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/aleksa/GA_CST/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/aleksa/GA_CST -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include timemeasurementthread.h -o moc_timemeasurementthread.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic \
		oblastcrtanjaopengl.h \
		algoritambaza.h \
		animacijanit.h \
		config.h
	/usr/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

algoritambaza.o: algoritambaza.cpp algoritambaza.h \
		animacijanit.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o algoritambaza.o algoritambaza.cpp

ga00_demoiscrtavanja.o: algoritmi_sa_vezbi/ga00_demoiscrtavanja.cpp algoritmi_sa_vezbi/ga00_demoiscrtavanja.h \
		algoritambaza.h \
		animacijanit.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ga00_demoiscrtavanja.o algoritmi_sa_vezbi/ga00_demoiscrtavanja.cpp

ga01_brisucaprava.o: algoritmi_sa_vezbi/ga01_brisucaprava.cpp algoritmi_sa_vezbi/ga01_brisucaprava.h \
		algoritambaza.h \
		animacijanit.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ga01_brisucaprava.o algoritmi_sa_vezbi/ga01_brisucaprava.cpp

ga02_3discrtavanje.o: algoritmi_sa_vezbi/ga02_3discrtavanje.cpp algoritmi_sa_vezbi/ga02_3discrtavanje.h \
		algoritambaza.h \
		animacijanit.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ga02_3discrtavanje.o algoritmi_sa_vezbi/ga02_3discrtavanje.cpp

ga03_konveksniomotac.o: algoritmi_sa_vezbi/ga03_konveksniomotac.cpp algoritmi_sa_vezbi/ga03_konveksniomotac.h \
		algoritambaza.h \
		animacijanit.h \
		config.h \
		pomocnefunkcije.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ga03_konveksniomotac.o algoritmi_sa_vezbi/ga03_konveksniomotac.cpp

ga04_konveksniomotac3d.o: algoritmi_sa_vezbi/ga04_konveksniomotac3d.cpp algoritmi_sa_vezbi/ga04_konveksniomotac3d.h \
		algoritambaza.h \
		animacijanit.h \
		config.h \
		algoritmi_sa_vezbi/ga04_konveksni3dDatastructures.h \
		pomocnefunkcije.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ga04_konveksniomotac3d.o algoritmi_sa_vezbi/ga04_konveksniomotac3d.cpp

ga05_preseciduzi.o: algoritmi_sa_vezbi/ga05_preseciduzi.cpp algoritmi_sa_vezbi/ga05_preseciduzi.h \
		algoritambaza.h \
		animacijanit.h \
		config.h \
		pomocnefunkcije.h \
		algoritmi_sa_vezbi/ga05_datastructures.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ga05_preseciduzi.o algoritmi_sa_vezbi/ga05_preseciduzi.cpp

ga06_dcel.o: algoritmi_sa_vezbi/ga06_dcel.cpp algoritmi_sa_vezbi/ga06_dcel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ga06_dcel.o algoritmi_sa_vezbi/ga06_dcel.cpp

ga06_dceldemo.o: algoritmi_sa_vezbi/ga06_dceldemo.cpp algoritmi_sa_vezbi/ga06_dceldemo.h \
		algoritambaza.h \
		animacijanit.h \
		config.h \
		pomocnefunkcije.h \
		algoritmi_sa_vezbi/ga06_dcel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ga06_dceldemo.o algoritmi_sa_vezbi/ga06_dceldemo.cpp

ga07_triangulation.o: algoritmi_sa_vezbi/ga07_triangulation.cpp algoritmi_sa_vezbi/ga07_triangulation.h \
		algoritambaza.h \
		animacijanit.h \
		config.h \
		pomocnefunkcije.h \
		algoritmi_sa_vezbi/ga07_datastructures.h \
		algoritmi_sa_vezbi/ga06_dcel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ga07_triangulation.o algoritmi_sa_vezbi/ga07_triangulation.cpp

constant_work_space.o: algoritmi_sa_vezbi/constant_work_space.cpp algoritmi_sa_vezbi/constant_work_space.h \
		algoritambaza.h \
		animacijanit.h \
		config.h \
		pomocnefunkcije.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o constant_work_space.o algoritmi_sa_vezbi/constant_work_space.cpp

ga06_presekPravougaonika.o: algoritmi_studentski_projekti/ga06_presekPravougaonika.cpp algoritmi_studentski_projekti/ga06_presekPravougaonika.h \
		algoritambaza.h \
		animacijanit.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ga06_presekPravougaonika.o algoritmi_studentski_projekti/ga06_presekPravougaonika.cpp

animacijanit.o: animacijanit.cpp animacijanit.h \
		algoritambaza.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animacijanit.o animacijanit.cpp

main.o: main.cpp mainwindow.h \
		algoritambaza.h \
		animacijanit.h \
		config.h \
		oblastcrtanja.h \
		oblastcrtanjaopengl.h \
		timemeasurementthread.h \
		algoritmi_sa_vezbi/ga00_demoiscrtavanja.h \
		algoritmi_sa_vezbi/ga01_brisucaprava.h \
		algoritmi_sa_vezbi/ga02_3discrtavanje.h \
		algoritmi_sa_vezbi/ga03_konveksniomotac.h \
		algoritmi_sa_vezbi/ga04_konveksniomotac3d.h \
		algoritmi_sa_vezbi/ga04_konveksni3dDatastructures.h \
		algoritmi_sa_vezbi/ga05_preseciduzi.h \
		pomocnefunkcije.h \
		algoritmi_sa_vezbi/ga05_datastructures.h \
		algoritmi_sa_vezbi/ga06_dceldemo.h \
		algoritmi_sa_vezbi/ga06_dcel.h \
		algoritmi_sa_vezbi/ga07_triangulation.h \
		algoritmi_sa_vezbi/ga07_datastructures.h \
		algoritmi_sa_vezbi/constant_work_space.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		algoritambaza.h \
		animacijanit.h \
		config.h \
		oblastcrtanja.h \
		oblastcrtanjaopengl.h \
		timemeasurementthread.h \
		algoritmi_sa_vezbi/ga00_demoiscrtavanja.h \
		algoritmi_sa_vezbi/ga01_brisucaprava.h \
		algoritmi_sa_vezbi/ga02_3discrtavanje.h \
		algoritmi_sa_vezbi/ga03_konveksniomotac.h \
		algoritmi_sa_vezbi/ga04_konveksniomotac3d.h \
		algoritmi_sa_vezbi/ga04_konveksni3dDatastructures.h \
		algoritmi_sa_vezbi/ga05_preseciduzi.h \
		pomocnefunkcije.h \
		algoritmi_sa_vezbi/ga05_datastructures.h \
		algoritmi_sa_vezbi/ga06_dceldemo.h \
		algoritmi_sa_vezbi/ga06_dcel.h \
		algoritmi_sa_vezbi/ga07_triangulation.h \
		algoritmi_sa_vezbi/ga07_datastructures.h \
		algoritmi_sa_vezbi/constant_work_space.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

oblastcrtanja.o: oblastcrtanja.cpp oblastcrtanja.h \
		algoritambaza.h \
		animacijanit.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oblastcrtanja.o oblastcrtanja.cpp

oblastcrtanjaopengl.o: oblastcrtanjaopengl.cpp oblastcrtanjaopengl.h \
		algoritambaza.h \
		animacijanit.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oblastcrtanjaopengl.o oblastcrtanjaopengl.cpp

pomocnefunkcije.o: pomocnefunkcije.cpp pomocnefunkcije.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pomocnefunkcije.o pomocnefunkcije.cpp

timemeasurementthread.o: timemeasurementthread.cpp timemeasurementthread.h \
		algoritambaza.h \
		animacijanit.h \
		config.h \
		mainwindow.h \
		oblastcrtanja.h \
		oblastcrtanjaopengl.h \
		algoritmi_sa_vezbi/ga00_demoiscrtavanja.h \
		algoritmi_sa_vezbi/ga01_brisucaprava.h \
		algoritmi_sa_vezbi/ga02_3discrtavanje.h \
		algoritmi_sa_vezbi/ga03_konveksniomotac.h \
		algoritmi_sa_vezbi/ga04_konveksniomotac3d.h \
		algoritmi_sa_vezbi/ga04_konveksni3dDatastructures.h \
		algoritmi_sa_vezbi/ga05_preseciduzi.h \
		pomocnefunkcije.h \
		algoritmi_sa_vezbi/ga05_datastructures.h \
		algoritmi_sa_vezbi/ga06_dceldemo.h \
		algoritmi_sa_vezbi/ga06_dcel.h \
		algoritmi_sa_vezbi/ga07_triangulation.h \
		algoritmi_sa_vezbi/ga07_datastructures.h \
		algoritmi_sa_vezbi/constant_work_space.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timemeasurementthread.o timemeasurementthread.cpp

moc_algoritambaza.o: moc_algoritambaza.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_algoritambaza.o moc_algoritambaza.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_oblastcrtanja.o: moc_oblastcrtanja.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_oblastcrtanja.o moc_oblastcrtanja.cpp

moc_oblastcrtanjaopengl.o: moc_oblastcrtanjaopengl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_oblastcrtanjaopengl.o moc_oblastcrtanjaopengl.cpp

moc_timemeasurementthread.o: moc_timemeasurementthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_timemeasurementthread.o moc_timemeasurementthread.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/GA6/bin || mkdir -p $(INSTALL_ROOT)/opt/GA6/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/GA6/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/GA6/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/GA6/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/GA6/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

